name: tachidesk_sorayomi
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.8.1
  flutter_mobx: ^2.0.6+1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^4.2.7
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  mobx: ^2.0.7+5
  objectbox: ^1.6.0
  objectbox_flutter_libs: ^1.6.0
  package_info_plus: ^1.4.3
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pub_semver: ^2.1.1
  share_plus: ^4.0.10
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_flavorizr: ^2.1.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  go_router_builder: ^1.0.7
  json_serializable: ^6.3.1
  lints: ^2.0.0
  mobx_codegen: ^2.0.7
  objectbox_generator: ^1.6.0
# TODO Remove This on update to objectbox
dependency_overrides:
  analyzer: ">=4.2.0 <5.0.0"
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/launcher/
    - assets/locales/

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: data/local/generator

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
    ios: null

  flavors:
    stable:
      app:
        name: "Sorayomi"
        icon: assets/icons/launcher/sorayomi_icon.png

      android:
        applicationId: "com.suwayomi.tachidesk_sorayomi"

      ios:
        bundleId: "com.suwayomi.tachidesk_sorayomi"
        name: "Sorayomi"

    preview:
      app:
        name: "Sorayomi Preview"
        icon: assets/icons/launcher/sorayomi_preview_icon.png

      android:
        applicationId: "com.suwayomi.tachidesk_sorayomi.preview"
      ios:
        bundleId: "com.suwayomi.tachidesk_sorayomi.preview"
        name: "Sorayomi Preview"

# flutter_native_splash:
#   color: "#54C5F8"
#   branding: assets/icons/launcher/from_suwayomi.png
#   image: assets/icons/dark_icon.png
#   color_dark: "#01579B"
#   image_dark: assets/icons/light_icon.png
#   android_12:
#     icon_background_color: "#54C5F8"
#     icon_background_color_dark: "#01579B"
#     image: assets/icons/dark_icon.png
#     image_dark: assets/icons/light_icon.png
