import 'package:flutter/material.dart';

enum AppTheme {
  /// ~ Colors for Green Apple theme
  ///
  /// ~ Original color scheme by CarlosEsco, Jays2Kings and CrepeTF
  ///
  /// ~ M3 colors generated by Material Theme Builder (https:///goo.gle/material-theme-builder-web)
  ///
  /// ~
  ///
  /// ~ Key colors:
  ///
  /// ~ Primary #188140
  ///
  /// ~ Secondary #188140
  ///
  /// ~ Tertiary #D33131
  ///
  /// ~ Neutral #5D5F5B
  ///
  greenApple(
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF7ADB8F),
      onPrimary: Color(0xFF003915),
      primaryContainer: Color(0xFF005322),
      onPrimaryContainer: Color(0xFF96F8A9),
      secondary: Color(0xFF7ADB8F),
      onSecondary: Color(0xFF003915),
      secondaryContainer: Color(0xFF005322),
      onSecondaryContainer: Color(0xFF96F8A9),
      tertiary: Color(0xFFFFB3AA),
      onTertiary: Color(0xFF680006),
      tertiaryContainer: Color(0xFF93000D),
      onTertiaryContainer: Color(0xFFFFDAD5),
      background: Color(0xFF1A1C19),
      onBackground: Color(0xFFE1E3DD),
      surface: Color(0xFF1A1C19),
      onSurface: Color(0xFFE1E3DD),
      surfaceVariant: Color(0xFF414941),
      onSurfaceVariant: Color(0xFFC1C8BE),
      outline: Color(0xFF8B9389),
      onInverseSurface: Color(0xFF1A1C19),
      inverseSurface: Color(0xFFE1E3DD),
      inversePrimary: Color(0xFF006D2F),
      error: Color(0xFFFFB4A9),
      onError: Color(0xFF680003),
      errorContainer: Color(0xFF930006),
      onErrorContainer: Color(0xFFFFDAD4),
    ),
  ),

  /// ~ Colors for Midnight Dusk theme
  ///
  /// ~ Original color scheme by CrepeTF
  ///
  /// ~ M3 color scheme generated by Material Theme Builder (https:///goo.gle/material-theme-builder-web)
  ///
  /// ~
  ///
  /// ~ Key colors:
  ///
  /// ~ Primary #F02475
  ///
  /// ~ Secondary #F02475
  ///
  /// ~ Tertiary #7A5733
  ///
  /// ~ Neutral #16151D
  ///
  midNightDusk(
    colorScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFF02475),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFBD1C5C),
      onPrimaryContainer: Color(0xFFFFFFFF),
      secondary: Color(0xFFF02475),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF02475),
      onSecondaryContainer: Color(0xFFFFFFFF),
      tertiary: Color(0xFF55971C),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFF386412),
      onTertiaryContainer: Color(0xFFE5E1E5),
      background: Color(0xFF16151D),
      onBackground: Color(0xFFE5E1E5),
      surface: Color(0xFF16151D),
      onSurface: Color(0xFFE5E1E5),
      surfaceVariant: Color(0xFF524346),
      onSurfaceVariant: Color(0xFFD6C1C4),
      outline: Color(0xFF9F8C8F),
      inverseSurface: Color(0xFF333043),
      onInverseSurface: Color(0xFFFFFFFF),
      inversePrimary: Color(0xFFF02475),
      error: Color(0xFFFFB4A9),
      onError: Color(0xFF680003),
      errorContainer: Color(0xFF930006),
      onErrorContainer: Color(0xFFFFDAD4),
    ),
  ),
  strawberry(
    colorScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFB61E40),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDADD),
      onPrimaryContainer: Color(0xFF40000D),
      secondary: Color(0xFFB61E40),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDADD),
      onSecondaryContainer: Color(0xFF40000D),
      tertiary: Color(0xFF775930),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDDB1),
      onTertiaryContainer: Color(0xFF2A1800),
      background: Color(0xFFFCFCFC),
      onBackground: Color(0xFF201A1A),
      surface: Color(0xFFFCFCFC),
      onSurface: Color(0xFF201A1A),
      surfaceVariant: Color(0xFFF4DDDD),
      onSurfaceVariant: Color(0xFF534344),
      outline: Color(0xFF857374),
      onInverseSurface: Color(0xFFFBEDED),
      inverseSurface: Color(0xFF362F2F),
      inversePrimary: Color(0xFFFFB2B9),
      error: Color(0xFFFFB4A9),
      onError: Color(0xFF680003),
      errorContainer: Color(0xFF930006),
      onErrorContainer: Color(0xFFFFDAD4),
    ),
  ),
  ;

  const AppTheme({required this.colorScheme});

  final ColorScheme colorScheme;
}
